In [2]:
import pandas as pd
d = pd.DataFrame({"A":[1,2,3,4], "B":[1,2,3,4]})
d

   A  B
0  1  1
1  2  2
2  3  3
3  4  4

In [6]:
d["C"] = d["A"]+d["B"]
d
d["C"] = d["A"]-d["B"]
d

   A  B  C
0  1  1  0
1  2  2  0
2  3  3  0
3  4  4  0

In [10]:
d = pd.DataFrame({"A":[12,20,30,40], "B":[13,23,33,40]})
d["Output"] = d["A"] == 30
d["Output2"] = d["B"] == 13
d

    A   B  Output  Output2
0  12  13   False     True
1  20  23   False    False
2  30  33    True    False
3  40  40   False    False