In [6]:
import pandas as pd
d = pd.DataFrame({"A":[1,2,3,4,5], "B":[7,8,5,4,3]})
d

   A  B
0  1  7
1  2  8
2  3  5
3  4  4
4  5  3

# Insert

In [28]:
d1 = pd.DataFrame({"A":[1,2,3,4], "B":[6,5,4,3]})
d1
print()
d1["C"] = d1["A"]+d1["B"]
d1

   A  B  C
0  1  6  7
1  2  5  7
2  3  4  7
3  4  3  7

In [49]:
d1["Output"] = d1["A"][:3]
d1

   A  B  C  Output
0  1  6  7     1.0
1  2  5  7     2.0
2  3  4  7     3.0
3  4  3  7     NaN

# Delete

In [75]:
d3 = pd.DataFrame({"apple":['a','p','p','l','e'], "balls":['b','a','l','l','s'], "catch":['c','a','t','c','h']})
d3

  apple balls catch
0     a     b     c
1     p     a     a
2     p     l     t
3     l     l     c
4     e     s     h

In [81]:
del d3["apple"]

In [83]:
d3

  balls catch
0     b     c
1     a     a
2     l     t
3     l     c
4     s     h